version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Packages (yarn install)
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn test

      - run:
          name: Avoid hosts unknown
          command: echo -e "Host naboo.deploy.umbler.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - add_ssh_keys:
          fingerprints:
            - "36:5e:58:17:19:b7:55:03:fd:a7:5f:bb:07:f4:1a:32"

      - run:
          name: Deploy to Umbler
          command: git remote add umbler ssh://git@naboo.deploy.umbler.com:9922/6j571vye/automatedhouse-top.git && git push umbler master
